import "./globals.css";

import { Settings } from "luxon";
import type { Metadata } from "next";

Settings.defaultZone = "Asia/Tokyo";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>{children}</body>
    </html>
  );
}
